pandoc 上岸指南V20241106.md \
    -o 上岸指南V20241106.pdf \
    --pdf-engine=xelatex \
    --toc \
    --toc-depth=3 \
    --number-sections \
    -V geometry:margin=1in \
    -V papersize=a4 \
    -V mainfont="SimSun" \
    -V monofont="DejaVu Sans Mono" \
    -V CJKmainfont="SimSun" \
    -V documentclass=article \
    -V fontsize=11pt \
    -V linestretch=1.2